src/java/model/Product.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

/**
 *
 * @author Viet
 */
public class Product {

    public Product() {
    }

    public Product(int productId, String productName, String productType, float price) {
        this.productId = productId;
        this.productName = productName;
        this.productType = productType;
        this.price = price;
    }
    
    private int productId;
    private String productName;
    private String productType;
    private float price;

    public int getProductId() {
        return productId;
    }

    public void setProductId(int productId) {
        this.productId = productId;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getProductType() {
        return productType;
    }

    public void setProductType(String productType) {
        this.productType = productType;
    }

    public float getPrice() {
        return price;
    }

    public void setPrice(float price) {
        this.price = price;
    }
    
    private int Quantity;

    public int getQuantity() {
        return Quantity;
    }

    public void setQuantity(int Quantity) {
        this.Quantity = Quantity;
    }
    
}

web/cart.jsp
<%-- 
    Document   : cart
    Created on : Dec 16, 2019, 9:48:12 AM
    Author     : Viet
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<jsp:useBean id="prod" class="model.ProductCart" scope="session"/>
<center>
    <table bgcolor="lightgreen" border="1" cellspacing="0" cellpadding="0">
        <tr>
            <td> <b> Product Id </b> </td>
            <td> <b> Product Name </b> </td>
            <td> <b> Product Type </b> </td>
            <td> <b> Price </b> </td>
            <td> <b> Quantity </b> </td>
            <td> </td>
        </tr>
        <c:forEach var="item" items="${prod.cartItems}">
            <tr>
                <td>${item.productId} </td>
                <td>${item.productName} </td>
                <td>${item.productType} </td>
                <td>${item.price} </td>
                <td>${item.quantity} </td>
                <td>
                    <form action="ShoppingServlet" name="deleteForm" method="POST">
                        <input type="submit" value="Delete">
                        <input type="hidden" name="delItem" value="${item.productId}">
                        <input type="hidden" name="action" value="DELETE">
                    </form>
                </td>
            </tr>
        </c:forEach>
    </table>
    <form name="checkOutForm" action="ShoppingServlet" method="POST">
        <input type="hidden" name="action" value="CHECKOUT"/>
        <input type="submit" name="Checkout" value="Checkout"/>
    </form>
</center>

web/checkout.jsp
<%-- 
    Document   : checkout
    Created on : Dec 16, 2019, 10:01:05 AM
    Author     : Viet
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<jsp:useBean id="prod" class="model.ProductCart" scope="session"/>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Transaction</title>
    </head>
    <body bgcolor="#FFFFCC">
        <h1>Transaction Details.</h1>
        <center>
            <table>
                <tr>
                    <td> <b> Product Id </b> </td>
                    <td> <b> Product Name </b> </td>
                    <td> <b> Product Type </b> </td>
                    <td> <b> Price </b> </td>
                    <td> <b> Quantity </b> </td>
                </tr>
                <c:forEach var="item" items="${prod.cartItems}">
                <tr>
                    <td>${item.productId} </td>
                    <td>${item.productName} </td>
                    <td>${item.productType} </td>
                    <td>${item.price} </td>
                    <td>${item.quantity} </td>
                </tr>
                </c:forEach>
                <tr>
                    <td></td>
                    <td></td>
                    <td><b> Total </b></td>
                    <td><b> ${prod.amount} </b></td>
                    <td></td>
                </tr>
            </table>
            <br/><br/>
            <h3>Customer Information</h3>
            <form action="ShoppingServlet" name="proceedForm" method="POST">
                Name: <input type="text" name="name"/><br/><br/>
                Email: <input type="text" name="email"/><br/><br/>
                Phone: <input type="text" name="phone"/><br/><br/>
                <a href="index.jsp">Back</a>
                <input type="hidden" name="action" value="PROCEED"/>
                <input type="submit" name="Proceed" value="Proceed"/>
            </form>
            <br>
        </center>
    </body>
</html>

web/index.jsp
<%-- 
    Document   : index
    Created on : Dec 16, 2019, 9:00:48 AM
    Author     : Viet
--%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Order Product</title>
    </head>
    <body bgcolor="#FFFFCC">
        <h1>Welcome to Shop Stop !!!</h1>
        <hr/>
        <jsp:useBean id="prod" class="model.ProductCart" scope="session"/>
        <form action="ShoppingServlet" name="shoppingForm" method="POST">
            <b> Products </b> <br>
            <select name="products">
                <c:forEach var="item" items="${prod.products}">
                    <option>
                        ${item.productId}${"|"}${item.productName}${"|"}${item.productType}${"|"}${item.price}
                    </option>
                </c:forEach>
            </select>
            <br> <br>
            <b> Quantity </b> <input type="text" name="qty" value="1"> <br>
            <input type="hidden" name="action" value="ADD">
            <input type="submit" name="Submit" value="Add to Cart">
        </form>
        <p>${message}</p>
        <c:if test="${size == 1}">
            <jsp:include page="cart.jsp" flush="true"/>
        </c:if>
    </body>
</html>

web/proceed.jsp
<%-- 
    Document   : proceed
    Created on : Dec 16, 2019, 10:54:23 PM
    Author     : Viet
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<jsp:useBean id="prod" class="model.ProductCart" scope="session"/>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body bgcolor="#FFFFCC">
        <h1>Bill Details.</h1>
        <center>
            <p>Total: ${prod.amount}</p>
            <p>Name: ${name}</p>
            <p>Email: ${email}</p>
            <p>Phone: ${phone}</p>
        </center>
    </body>
</html>

web/shoppingError.jsp
<%-- 
    Document   : shoppingError
    Created on : Dec 16, 2019, 9:59:23 AM
    Author     : Viet
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Shopping</title>
    </head>
    <body>
        <h1>Error Occurred</h1>
        ${message}
        <a href="index.jsp"> Home </a>
    </body>
</html>